services:
  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    working_dir: '/usr/src/app'
    tty: true
    command: python manage.py runserver 0.0.0.0:8000  # サーバー起動コマンドを追加
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8000"
    depends_on:
      - db  # dbサービスが先に起動している必要がある

  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    tty: true
    volumes:
      - ./infra/db/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # ホストのポート80をNginXにマッピング
    volumes:
      - ./infra/nginx/fnginx.conf:/etc/nginx/conf.d/default.conf  # NginX設定ファイルのマウント
      - ./static:/usr/src/app/static  # 静的ファイルをマウント
    depends_on:
      - app  # appサービスが先に起動している必要がある


  
